const fs = require('fs');
const { Document, Packer, Paragraph, TextRun, HeadingLevel, ImageRun, Table, TableRow, TableCell,
        WidthType, AlignmentType, BorderStyle, ShadingType, LevelFormat, PageBreak, Footer, PageNumber } = require('docx');

const img = (f) => fs.readFileSync(f);
const T = (t, o = {}) => new TextRun({ text: t, ...o });
const P = (children, o = {}) => new Paragraph({ children: Array.isArray(children) ? children : [T(children)], spacing: { after: 120 }, ...o });
const H1 = (t) => new Paragraph({ text: t, heading: HeadingLevel.HEADING_1, spacing: { before: 280, after: 120 } });
const H2 = (t) => new Paragraph({ text: t, heading: HeadingLevel.HEADING_2, spacing: { before: 200, after: 100 } });
const bullet = (t) => new Paragraph({ children: Array.isArray(t) ? t : [T(t)], numbering: { reference: 'bul', level: 0 }, spacing: { after: 60 } });
const eq = (t) => new Paragraph({ children: [T(t, { italics: true })], alignment: AlignmentType.CENTER, spacing: { before: 80, after: 120 } });
const fig = (file, wpx, hpx, caption) => [
  new Paragraph({ children: [new ImageRun({ type: 'png', data: img(file), transformation: { width: wpx, height: hpx } })], alignment: AlignmentType.CENTER, spacing: { before: 160, after: 60 } }),
  new Paragraph({ children: caption, spacing: { after: 240 }, alignment: AlignmentType.LEFT })
];
const cap = (label, text) => [T(label, { bold: true, size: 18 }), T(' ' + text, { size: 18 })];

const cellB = { top: { style: BorderStyle.SINGLE, size: 4, color: 'BFBFBF' }, bottom: { style: BorderStyle.SINGLE, size: 4, color: 'BFBFBF' },
                left: { style: BorderStyle.NONE, size: 0 }, right: { style: BorderStyle.NONE, size: 0 } };
function table(header, rows, widths) {
  const total = widths.reduce((a, b) => a + b, 0);
  const mk = (txt, w, bold, shade) => new TableCell({
    width: { size: w, type: WidthType.DXA }, borders: cellB, margins: { top: 40, bottom: 40, left: 80, right: 80 },
    shading: shade ? { type: ShadingType.CLEAR, fill: 'F2F2F0', color: 'auto' } : undefined,
    children: [new Paragraph({ children: [T(String(txt), { bold, size: 18 })], spacing: { after: 0 } })] });
  return new Table({ width: { size: total, type: WidthType.DXA }, columnWidths: widths,
    rows: [new TableRow({ tableHeader: true, children: header.map((h, i) => mk(h, widths[i], true, true)) }),
           ...rows.map(r => new TableRow({ children: r.map((c, i) => mk(c, widths[i], false, false)) }))] });
}
const tcap = (label, text) => new Paragraph({ children: cap(label, text), spacing: { before: 160, after: 80 } });

const doc = new Document({
  styles: { default: { document: { run: { font: 'Calibri', size: 22 } } },
    paragraphStyles: [
      { id: 'Heading1', name: 'Heading 1', basedOn: 'Normal', next: 'Normal', quickFormat: true, run: { size: 30, bold: true, color: '1F1F1F', font: 'Calibri' }, paragraph: { spacing: { before: 280, after: 120 }, outlineLevel: 0 } },
      { id: 'Heading2', name: 'Heading 2', basedOn: 'Normal', next: 'Normal', quickFormat: true, run: { size: 25, bold: true, color: '333333', font: 'Calibri' }, paragraph: { spacing: { before: 200, after: 100 }, outlineLevel: 1 } }] },
  numbering: { config: [{ reference: 'bul', levels: [{ level: 0, format: LevelFormat.BULLET, text: '\u2022', alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 540, hanging: 270 } } } }] }] },
  sections: [{
    properties: { page: { size: { width: 12240, height: 15840 }, margin: { top: 1300, bottom: 1300, left: 1400, right: 1400 } } },
    footers: { default: new Footer({ children: [new Paragraph({ alignment: AlignmentType.CENTER, children: [T('SCM-PIT two-domain bias survey — analysis note, 20 Sep 2026 — p. ', { size: 16, color: '777777' }), new TextRun({ children: [PageNumber.CURRENT], size: 16, color: '777777' })] })] }) },
    children: [
      new Paragraph({ children: [T('Removing the cantilever from contact-resonance PFM: position-resolved recovery of d\u2083\u2083 and contact potential on periodically poled LiNbO\u2083', { bold: true, size: 34 })], spacing: { after: 160 } }),
      P([T('Analysis note on the SCM-PIT two-domain bias survey of 20 September 2026 (DomainsB_SCMPIT, stage 1). Prepared for L. Collins, CNMS / ORNL. Draft for internal discussion; numbers are as extracted from the raw checkpoint and are reproducible from the scripts listed in the Methods.', { italics: true, color: '555555', size: 20 })]),

      H1('Abstract'),
      P('A single-frequency piezoresponse force microscopy (PFM) amplitude cannot be converted to a piezoelectric coefficient without knowing how the cantilever turns a tip displacement into a detected signal. That transfer depends on where along the lever the detection spot sits and on which contact-resonance mode is being driven, and it is usually replaced by a single factor Q. We measured the full complex response of an SCM-PIT probe (k = 1.697 N/m) on two antiparallel domains of periodically poled LiNbO\u2083 at eight positions along the lever, seven tip biases from \u22129 to +9 V, and 58\u202f816 frequencies from 100 Hz to 2 MHz, at a load of 500 nN. The two-domain design separates the piezoresponse P (which changes sign between domains) from the electrostatic response b (which does not) exactly, per position and per frequency, and returns the contact potential V\u2098\u209a\u2091 = +0.77 \u00b1 0.11 V from the first contact resonance (CR1, 285.5 kHz). In the quasi-static band (15\u201345 kHz) the piezoresponse converts directly through the per-position force-curve sensitivity to d\u2083\u2083 = 8.0 pm/V (7.6\u20139.2 across 180 \u00b5m of lever). At CR1 the resonance enhancement over the quasi-static response runs from 2.8 at the free end to 506 near the base, so dividing by Q (191) returns anything from 0.15 to 23 pm/V. An Euler\u2013Bernoulli (EB) contact-resonance model fitted only to the three contact-resonance frequencies, the CR1 quality factor and the static deflection shape predicts that enhancement to within 0.98\u20131.14\u00d7 at all seven interior positions, and converts the CR1 amplitude to d\u2083\u2083 = 7.97 pm/V with a 1.07\u00d7 spread (sd 2.0 %), using a single detector calibration at the free end. The same model predicts the CR2 and CR3 mode shapes and node positions correctly but under-predicts their modal gain by constant factors of 2.8 and 5.5; with one gain per mode the higher modes return 8.9 and 8.4 pm/V. The distributed electrostatic load in the model also reproduces the measured position dependence of |b|/|P| in both bands. The approach fails only at a node of the mode being used, where a micron of node error is a factor of two in amplitude.'),

      H1('1. Motivation'),
      P('In PFM the measured signal at a detection position x and drive frequency f is Z(x, f) = H(x, f) \u00b7 u\u209c\u1d62\u209a, where u\u209c\u1d62\u209a is the surface displacement under the tip (d\u2083\u2083 V\u2090\u1d9c for an ideal piezoelectric contact plus an electrostatic term) and H is the cantilever\u2019s transfer function from tip displacement to detected displacement. Quantitative PFM requires removing H. In practice H is replaced by the static inverse optical lever sensitivity (InvOLS) measured at one position, times a quality factor if the drive is on a contact resonance. Both shortcuts are wrong in general: the static sensitivity depends on x, the on-resonance sensitivity depends on x through the mode shape, and the two dependences differ. On a displacement-detecting instrument (the Cypher\u2019s quadrature phase differential interferometer, QPDI) these effects are cleanly separable because the detector reads displacement directly with a fixed metres-per-volt constant, so every position dependence in the signal is the cantilever\u2019s.'),
      P('A measurement that moves the detection spot along the lever therefore samples H(x, f) directly. Combined with a two-domain design that removes electrostatics without a model, it lets the cantilever physics be tested rather than assumed. The questions addressed here are: (i) does the quasi-static piezoresponse convert to a position-independent d\u2083\u2083 through the per-position InvOLS; (ii) what is the actual resonance enhancement at CR1 as a function of position, and is it Q; (iii) can an EB contact-resonance model, constrained only by frequencies, Q and the static shape, predict that enhancement well enough to recover d\u2083\u2083 from a resonance measurement alone; and (iv) does this extend to higher modes.'),

      H1('2. Experiment'),
      H2('2.1 Probe and calibration'),
      P('The probe is a Nanosensors SCM-PIT (Pt/Ir-coated). Free-air thermal calibration immediately before the run (TuneNCCal0000.ibw, 11:22) gave k = 1.697 N/m, f\u2080 = 63.801 kHz, Q\u2080 = 175, an end-of-lever InvOLS of 5.872 \u00d7 10\u207b\u2077 m/V and an AC amplitude sensitivity AmpInvOLS of 1.835 \u00d7 10\u207b\u2078 m/V. Their ratio, 32.00, is the fixed gain between the DC deflection path and the AC (lock-in) path of this instrument; it was also found to be 32.000 \u00b1 0.001 on an earlier probe from wave-note statistics, and here it is measured directly for the probe used. It is the only quantity in the d\u2083\u2083 chain that is not measured per position.'),
      P('In contact at 500 nN (deflection 295 nm, setpoint 0.593 V at the free end) the first three contact resonances at the free end are CR1 = 285.50 kHz, CR2 = 885.95 kHz and CR3 = 1705.89 kHz, with CR2/CR1 = 3.103 (the earlier SCM-PIT on the same sample gave 904/293 = 3.085). The panel spring constant read 1.6971 N/m throughout.'),
      H2('2.2 Sample, positions and acquisition'),
      P('The sample is periodically poled LiNbO\u2083 (DomainsB). Two spots were marked on a PFM image, one in each of two antiparallel domains, and the scanner was driven to them with the Cypher\u2019s GoToSpot. The detection spot was parked at the free end of the lever and moved toward the clamped base with the laser-diode stage in relative steps; a pre-flight walk in 10 \u00b5m steps established the reachable range as 52\u2013232 \u00b5m in the stage\u2019s own coordinate (78 % of the lever; the walk stopped on an InvOLS guard, not on signal). Eight positions equispaced over that range were measured, free end first. At each position the sequence was: withdraw, move, optical image, AutoWedge, force curve (InvOLS), then for each of 14 conditions engage at 500 nN and acquire one 2 MHz tune. Conditions were the two spots as the outer loop and seven biases [\u22129, \u22126, \u22123, 0, +3, +6, +9] V in interleaved order (0, +9, \u22129, +6, \u22126, +3, \u22123) so that drift appears as scatter rather than slope. Bias was applied to the tip (td_wv("TipBias")). The drive was 1.0 V on the tip; the tune sweeps 100 Hz \u2013 2.000066 MHz in 58\u202f816 points (34 Hz step) in 10 s. The whole survey took 45.2 min and returned 14 \u00d7 8 \u00d7 58\u202f816 complex spectra with no missing entries. Acquisition was scripted (activemodemap package, run_series with a fixed design) and checkpointed per position.'),
      H2('2.3 Position calibration'),
      P('The stage coordinate x is tracked in software from relative moves. Two facts pin the physical axis. First, the spot at x = 232 is at the free end: the CR1 amplitude collapses there (Sec. 5.3), which only happens at the node of a pinned tip. Second, the force-curve sensitivity 1/InvOLS(x) must follow the static end-loaded deflection shape (x\u2212x\u2080)\u00b2(3L\u2212(x\u2212x\u2080)) of a clamped beam; fitting only the clamp offset x\u2080 with the free end anchored gives x\u2080 = +6.1 \u00b5m and L = 225.9 \u00b5m, with a 3.1 % rms residual over eight positions (power-law exponent of 1/InvOLS vs x: 1.91). The recovered length is the SCM-PIT nominal (225 \u00b5m). All positions below are quoted as distance from the clamp on this calibrated axis: 225.9, 200.2, 174.5, 148.8, 123.0, 97.3, 71.6 and 45.9 \u00b5m.'),

      H1('3. Analysis'),
      H2('3.1 Two-domain decomposition'),
      P('At every position and frequency the response of domain s to bias V is linear, Z\u209b(V) = a\u209b + b\u209b V, and the two domains share the electrostatic term while the piezoresponse changes sign:'),
      eq('Z\u2081(V) = +P + b (V \u2212 V\u2098\u209a\u2091),      Z\u2082(V) = \u2212P + b (V \u2212 V\u2098\u209a\u2091)'),
      P('A complex least-squares line is fitted through the seven biases for each spot, then'),
      eq('P = (a\u2081 \u2212 a\u2082)/2,      b = (b\u2081 + b\u2082)/2,      V\u2098\u209a\u2091 = \u2212(a\u2081 + a\u2082)/(2b)'),
      P('This is exact per (x, f), requires no assumption about V\u2098\u209a\u2091, and yields a piezoresponse P that is free of electrostatics by construction. Two consistency checks follow from the model: b must be the same in both domains (|b\u2082/b\u2081| = 0.94\u20131.15 at CR1), and Z\u2081/Z\u2082 evaluated at V\u2098\u209a\u2091 must be \u2212P/P = 180\u00b0 (measured 168\u2013177\u00b0 at every position and mode). The fit residual at CR1 is 7\u201310 % of |Z|. V\u2098\u209a\u2091 is a ratio of fitted coefficients and therefore independent of the cantilever transfer; it is well determined only where |b| is measurable.'),
      H2('3.2 Quasi-static conversion'),
      P('|P| is flat within 4 % from 2 kHz to 220 kHz at the free end, a genuine quasi-static plateau below CR1 (Sec. 5.3). In the band 15\u201345 kHz the conversion to a piezoelectric coefficient is'),
      eq('d\u2083\u2083(x) = |P(x)|\u2081\u2085\u208b\u2084\u2085 \u2096\u2095\u1d22 \u00b7 InvOLS(x) / 32 / V\u2090\u1d9c'),
      P('with InvOLS(x) recomputed from the force curve taken at that position rather than read from the wave note (the note lags one position, confirmed again here for every file). Because the interferometer reads displacement with a fixed constant, InvOLS(x) is itself the local static transfer function, so this conversion needs no beam model; it does need one force curve per position.'),
      H2('3.3 Resonance enhancement'),
      P('The enhancement of the piezoresponse at a contact resonance over the quasi-static value, E(x) = |P(x, f\u1d9c\u1d63)| / |P(x)|\u2096\u209b, is measured directly. Q at CR1 is taken from the FWHM of |P| at each position. If dividing by Q were the correct correction, E/Q would be 1 everywhere.'),
      H2('3.4 Euler\u2013Bernoulli model and blind fit'),
      P('The forward model is the package\u2019s assumed-modes EB solver (activemodemap.forward_model.EBForwardModel, 14 clamped-free modes): a clamped-free beam of length L with the tip contact at x\u1d9c = L \u2212 \u0394 (setback \u0394), a vertical contact spring k* and a lateral spring k\u1d9c\u2092\u2099\u2091 coupled through the tip height h and an 11\u00b0 tilt, a contact dashpot, intrinsic modal damping \u03b6, tip mass 3 % of the beam mass, and two drive pathways: a tip displacement (piezo) applied through the contact spring, and a distributed electrostatic load q(\u03be) \u221d w\u2091\u1da0\u1da0(\u03be)/gap(\u03be)\u00b2 along the beam. Both response maps are normalised to unit quasi-static free-end displacement, so |z\u209a(x, f)| is the transfer function H relative to the free end at rest.'),
      P('Five parameters (log k*/k, log k\u1d9c\u2092\u2099\u2091/k, \u0394, log \u03b6, h) were fitted by least squares to: the three measured contact-resonance frequencies (weight 3), the static shape 1/InvOLS(x) at the seven interior positions (shape only, one free scale), and the CR1 quality factor at mid-lever. The CR1 enhancement data were given zero weight (\u201cblind\u201d). A second fit including E(x) with weight 0.5 is reported for comparison. Frequencies, Q and static shape fix L, x\u1d9c, k* and \u03b6 well; k\u1d9c\u2092\u2099\u2091 and h are degenerate (only their coupling product matters) and are not interpreted.'),
      P('The blind fit gives k*/k = 482, k\u1d9c\u2092\u2099\u2091/k = 1.3, \u0394 = 2.9 \u00b5m, \u03b6 = 3.3 \u00d7 10\u207b\u00b3, h = 5.2 \u00b5m; frequencies within \u22120.46, +0.67 and +0.02 % of CR1\u20133; Q\u1d9c\u1d63\u2081 = 191 against 191 measured; static-shape rms 2.8 %. The fit including E gives k*/k = 442, k\u1d9c\u2092\u2099\u2091/k = 6.6, \u0394 = 4.1 \u00b5m, \u03b6 = 3.2 \u00d7 10\u207b\u00b3, h = 14.5 \u00b5m, frequencies within 1.5 %, Q 196.'),
      P('The model-based conversion of a resonance amplitude uses a single detector calibration, taken at the free end where the interferometer reads the tip displacement directly, and the model for everything else:'),
      eq('d\u2083\u2083(x) = |P(x, f\u1d9c\u1d63)| \u00b7 InvOLS(L)/32 / ( V\u2090\u1d9c \u00b7 |z\u209a(x, f\u1d9c\u1d63)| / |z\u209a(L, f\u21920)| )'),
      P('|z\u209a(x, f\u1d9c\u1d63)| is evaluated at the model\u2019s own resonance at each x (the maximum over a sweep of \u00b13 linewidths), not at the measured frequency: with a 1 % frequency error and Q \u2248 190 the two differ by a linewidth, and sampling the model off its peak biases d\u2083\u2083 upward by ~12 %.'),

      H1('4. Results'),
      H2('4.1 Bias dependence'),
      ...fig('figA_bias_dependence.png', 660, 205, cap('Figure 1.', 'Two-domain bias dependence at 500 nN. |Z| versus tip bias for domain 1 (blue) and domain 2 (orange) at the eight detection positions (columns; distance from clamp), in the quasi-static band 15\u201345 kHz (top) and at the CR1 peak (bottom). Points are data; lines are |a\u209b + b\u209b V| from the complex fits. The two V-shapes are mirror images whose minima straddle V\u2098\u209a\u2091 at \u00b1|P|/|b|; the domains flip the sign of P and share b. At the free end the quasi-static response barely depends on bias (b \u2192 0 there) and the CR1 response is small because the free end is the CR1 node.')),
      P('Every panel shows the expected ferroelectric signature: two mirror-image |Z|(V) curves whose minima sit symmetrically on either side of the contact potential, not on it. The quasi-static minima move outward toward the free end because b vanishes there while P does not (Sec. 4.2). At CR1 the pattern is the same at every position and only the scale changes, from 3.5 mV at the free end to 160 mV at 123\u2013149 \u00b5m.'),
      H2('4.2 Contact potential and channel ratio'),
      ...fig('figB_cpd_channel_ratio.png', 660, 252, cap('Figure 2.', 'Left: V\u2098\u209a\u2091 recovered per position from the quasi-static band (blue) and at CR1 (orange); bars are the weighted spread across the band. Right: the electrostatic-to-piezo channel ratio |b|/|P| per volt in the two bands, with the EB model\u2019s ratio of electrostatic to piezo pathways scaled by one number per band (lines).')),
      P('CR1 gives V\u2098\u209a\u2091 = +0.77 \u00b1 0.11 V (median \u00b1 sd over positions; per-position 0.67 to 1.03 V with \u00b10.06\u20130.4 V across the band). The quasi-static band agrees where it is determined (+0.78 to +1.03 V from 46 to 200 \u00b5m) and is undetermined at the free end (\u00b15.7 V) because b vanishes there. The value is lower than the +1.51 V found with an Au-coated PPP-CONTAu on the same sample, as expected for a different tip coating.'),
      P('The channel ratio |b|/|P| is flat along the lever at CR1, 0.19\u20130.22 per volt, and rises monotonically from 0.015 at the free end to 0.47 at 46 \u00b5m in the quasi-static band. The EB model reproduces both curves with one scale factor each: the distributed electrostatic load on the cantilever body deflects the beam with a shape that differs from the tip-driven static shape, and their ratio grows toward the base; at CR1 the tip-driven mode dominates both pathways and the ratio is position-independent. Two practical consequences: the CPD is best extracted at CR1 anywhere along the lever, or quasi-statically only in the inner half; and a CR1 PFM measurement at 0 V on a single domain is biased low by a uniform 15 % (|Z\u2081(0)/P| = 0.80\u20130.86 at every position), whereas the same bias in the quasi-static band runs from 0 % at the free end to 34 % at the base.'),
      P('Relative to the PPP-CONTAu at 15 nN (|b|/|P| = 1.64, 0.24, 0.12 at CR1\u20133), the SCM-PIT at 500 nN gives 0.217, 0.025, 0.015 \u2014 a common factor of 0.11\u20130.13 at all three modes, consistent with the electrostatic force loading against a contact stiffness that is higher here, but not separable from the different tip radius and coating in this comparison.'),
      H2('4.3 The cantilever transfer function'),
      ...fig('figD_cantilever_transfer.png', 660, 252, cap('Figure 3.', 'Left: measured static shape 1/InvOLS(x) (blue points) and CR1 displacement shape |P(x, f\u1d9c\u1d63\u2081)| (orange squares; the QPDI reads displacement directly, so this is the mode shape in volts), each normalised, against the blind EB fit on the calibrated axis. Right: the CR1 enhancement over the quasi-static response, measured (points) and predicted by the EB model fitted without these data (solid) or with them (dashed); the horizontal line is the measured Q.')),
      P('|P(x, f\u1d9c\u1d63\u2081)| traces the CR1 mode shape: near zero at the free end (pinned tip), maximum at 120\u2013150 \u00b5m, decreasing toward the clamp. 1/InvOLS(x) traces the static end-loaded shape. Both overlay the blind EB fit (static rms 2.8 %). The enhancement E(x) runs from 2.8 at the free end to 506 at 46 \u00b5m, while Q is 153\u2013205 (191 median excluding the free end); E equals Q at one place only, x \u2248 149 \u00b5m. The blind model predicts E to within 0.98\u20131.14\u00d7 at the seven interior positions. At the free end it predicts 1.4 against 2.8 measured: a fraction of a micron of node position is a factor of two there.'),
      H2('4.4 Recovery of d\u2083\u2083'),
      ...fig('figC_d33_vs_position.png', 660, 252, cap('Figure 4.', 'Left: d\u2083\u2083 versus position from the quasi-static band with per-position InvOLS (blue), from CR1 with the blind EB transfer function and a single free-end calibration (orange), from CR1 with the EB fit that included the CR1 shape (green), and from the quasi-static band converted with the EB static shape and the free-end calibration only (yellow). Grey band 7.5\u20138.5 pm/V. Right: log scale, the same CR1 amplitudes divided by Q (pink) against the EB conversion (orange) and the quasi-static result (blue). Orange values in the left panel are from the fixed-frequency evaluation of the model; Table 2 gives the on-peak evaluation used in the text.')),
      tcap('Table 1.', 'Per-position quantities. x is distance from the clamp on the calibrated axis; |P|\u2096\u209b is the median over 15\u201345 kHz; d\u2083\u2083(qs) uses the per-position InvOLS; E is the measured CR1 enhancement and E\u2091\u1d66 the blind EB prediction; d\u2083\u2083(CR1, EB) is the model conversion with the free-end InvOLS only, model evaluated on its own peak.'),
      table(['x (\u00b5m)', 'InvOLS (m/V)', '|P|\u2096\u209b (\u00b5V)', 'd\u2083\u2083 qs (pm/V)', 'E meas', 'E\u2091\u1d66 blind', 'Q', 'd\u2083\u2083 CR1/Q', 'd\u2083\u2083 CR1, EB'],
        [['225.9 (free end)', '5.43e-7', '466', '7.90', '2.8', '1.6', '153', '0.15', '13.8 (node)'],
         ['200.2', '6.09e-7', '399', '7.59', '54.9', '55.1', '200', '2.18', '8.10'],
         ['174.5', '7.52e-7', '326', '7.66', '121.8', '126.0', '195', '4.89', '7.97'],
         ['148.8', '9.82e-7', '255', '7.84', '200.2', '209.2', '195', '8.22', '8.04'],
         ['123.0', '1.39e-6', '188', '8.14', '275.9', '301.6', '195', '11.77', '7.85'],
         ['97.3', '2.11e-6', '130', '8.57', '367.8', '398.3', '205', '15.77', '8.32'],
         ['71.6', '3.80e-6', '74.5', '8.85', '432.2', '495.7', '200', '19.13', '7.93'],
         ['45.9', '9.17e-6', '32.0', '9.17', '505.9', '590.4', '204', '23.31', '7.80'],
         ['median / spread (interior)', '', '', '8.14 / 1.21\u00d7', '', '', '', '11.8 / 10.7\u00d7', '7.97 / 1.07\u00d7']],
        [1500, 1050, 950, 1100, 800, 900, 600, 1050, 1300]),
      P(''),
      P('The quasi-static chain gives d\u2083\u2083 = 7.90 pm/V at the free end, where no shape enters at all, and 7.6\u20139.2 pm/V along the lever (median 8.0, sd 0.55, spread 1.21\u00d7). The mild rise toward the base is the residual disagreement between |P|\u2096\u209b(x), which falls 14.5\u00d7 from tip to base, and 1/InvOLS(x), which falls 16.9\u00d7; the most likely cause is the assumption that the AC/DC path ratio is exactly 32 at every position, since it was measured at the free end. Converting the quasi-static |P| with the EB static shape and the free-end InvOLS alone gives 8.3 pm/V with a 1.08\u00d7 spread \u2014 tighter than using eight separate force curves.'),
      P('Dividing the CR1 amplitude by Q gives 0.15\u201323 pm/V, a 160\u00d7 range, and agrees with the quasi-static value only at the single position where E = Q. Dividing by the blind EB transfer function instead gives 7.97 pm/V with a 1.07\u00d7 spread and 2.0 % sd over the seven interior positions, against 8.02 pm/V for the quasi-static median: agreement to 1 %, with one calibration constant instead of eight. Including the CR1 shape in the fit does not improve this (8.58, 1.09\u00d7, 2.8 %). The free end is excluded: it is the CR1 node, and the blind model returns 13.8 pm/V there.'),
      H2('4.5 Higher modes'),
      ...fig('figE_higher_modes.png', 660, 366, cap('Figure 5.', 'Top: measured enhancement over quasi-static at CR1, CR2 and CR3 (filled points; open points are positions within a quarter of the mode\u2019s peak amplitude of a node and are excluded from statistics) against the blind EB prediction as computed (dashed) and scaled by one factor per mode (solid). Bottom: d\u2083\u2083 recovered from each mode with the EB transfer as computed (filled squares) and with the per-mode factor (open diamonds), against the quasi-static result (blue line). Measured and model Q are given in the panel titles.')),
      tcap('Table 2.', 'Higher-mode summary. Gain is the median of E\u2098\u2091\u2090\u209b/E\u2091\u1d66 away from nodes. d\u2083\u2083 values are medians over positions away from nodes.'),
      table(['mode', 'f meas / model (kHz)', 'Q meas / model', 'nodes predicted (\u00b5m)', 'gain E\u2098\u2091\u2090\u209b/E\u2091\u1d66', 'n', 'd\u2083\u2083 as computed', 'd\u2083\u2083 with gain', 'spread'],
        [['CR1', '285.5 / 284.2', '191 / 193', '226 (free end)', '0.92', '7', '7.97', '8.6', '1.07\u00d7'],
         ['CR2', '885.9 / 891.9', '186 / 170', '\u2248125', '2.79', '6', '24.9', '8.9', '1.24\u00d7'],
         ['CR3', '1705.9 / 1706.2', '114 / 117', '\u224892, \u2248165', '5.51', '7', '46.3', '8.4', '1.29\u00d7']],
        [700, 1500, 1100, 1500, 1100, 400, 1100, 1000, 850]),
      P(''),
      P('The model gets the mode shapes right at CR2 and CR3: the interior node predicted near 125 \u00b5m for CR2 coincides with the measured minimum at 123 \u00b5m, and the two CR3 nodes predicted near 92 and 165 \u00b5m coincide with the minima at 97 and 175 \u00b5m; away from nodes the shape of E(x) is reproduced to the same precision as at CR1. What it does not get right is the absolute modal gain: the measured response at CR2 is 2.8\u00d7 and at CR3 5.5\u00d7 larger than the model predicts, uniformly along the lever, even though the model\u2019s Q at each mode is within 10 % of the measured one. With one empirical gain per mode the higher modes return 8.9 and 8.4 pm/V, spreads 1.24\u00d7 and 1.29\u00d7. A mode-2 gain excess of this size (\u22129.5 dB, a factor 3.0) was found independently in the SCM-PIT Dense_Grid_A study, where a per-band gain was needed to fit CR1 and CR2 together. The sign rules out detector roll-off, which would make the measured higher modes smaller, not larger, than predicted. Candidates are the modal projection of the drive (a tilted tip driven by a vertical surface displacement also drives the beam through the slope coupling, whose weight grows with mode number) or a component of in-plane surface motion (d\u2081\u2085 shear) coupling through the lateral spring; the present data cannot separate these.'),

      H1('5. Discussion'),
      bullet([T('The two-domain decomposition is the enabling step. ', { bold: true }), T('It removes electrostatics exactly, per position and frequency, and the resulting P is what any conversion should start from. Both consistency checks (b domain-independent, 180\u00b0 flip at V\u2098\u209a\u2091) pass at every position and mode. It also gives the CPD as a by-product, without the cantilever entering.')]),
      bullet([T('The quasi-static band is already quantitative without a beam model ', { bold: true }), T('if one force curve per position is taken and the AC/DC path ratio is known: 8.0 pm/V, 1.21\u00d7 spread over 180 \u00b5m. The free-end value (7.90) is the most model-free number in this note. It sits between bulk LiNbO\u2083 d\u2083\u2083 (\u22486 pm/V), the earlier SCM-PIT value on this sample (6.9 \u00b1 0.2) and the \u224810 pm/V from imaging on the same day.')]),
      bullet([T('The resonance enhancement is a position, not a number. ', { bold: true }), T('E(x) spans 2.8\u2013506 at CR1 while Q is constant; it equals Q at one point. Dividing by Q is not an approximation that degrades gracefully, it is wrong by orders of magnitude at either end of the lever. In particular, with the spot parked at the free end \u2014 the usual PFM configuration \u2014 CR1 gives almost no gain on a probe whose pinned tip puts the node there.')]),
      bullet([T('An EB model fitted blind to the resonance data removes the cantilever at CR1 to 1\u20137 %. ', { bold: true }), T('The inputs are things any PFM experiment can measure in minutes: three resonance frequencies, one Q, and a few force curves along the lever (or, in principle, the InvOLS at two or three positions to fix L and x\u1d9c). The conversion then needs one detector calibration at the free end. The resulting 1.07\u00d7 spread is tighter than the quasi-static chain\u2019s 1.21\u00d7 because it does not inherit eight force-curve measurements.')]),
      bullet([T('The model must be evaluated on its own peak. ', { bold: true }), T('A 1 % frequency error is a linewidth at Q = 190; sampling the model at the measured frequency biased d\u2083\u2083 by +12 % in a first pass.')]),
      bullet([T('Higher modes: shapes yes, gains no. ', { bold: true }), T('The EB model predicts the CR2 and CR3 mode shapes and node positions but under-predicts their gain by 2.8\u00d7 and 5.5\u00d7. Until the drive coupling at higher modes is understood, a per-mode gain has to be calibrated once (e.g. from the quasi-static band at one position). With that, all three modes agree on d\u2083\u2083 to within 10 %.')]),
      bullet([T('Nodes are excluded, not corrected. ', { bold: true }), T('Where the mode being used has a node, a sub-micron error in the predicted node position is a factor of two in amplitude. The free end is the CR1 node for a pinned tip; CR2 and CR3 have interior nodes at 125 and 92/165 \u00b5m on this lever. A position-swept measurement identifies these; a single-position measurement cannot.')]),
      bullet([T('Open items. ', { bold: true }), T('(i) The \u00f732 AC/DC path ratio is measured only at the free end; the residual +16 % slope in the quasi-static d\u2083\u2083 toward the base is consistent with it varying by that much and can be checked by moving the force-curve drive off resonance and comparing the force-curve AC channel with the tune amplitude at each position. (ii) The per-mode gain excess needs a physical model; the joint fit\u2019s degeneracy between k\u1d9c\u2092\u2099\u2091 and h means the lateral coupling is not constrained by this data set. (iii) The 1 \u00b5m dense map of the same lever (stage 3, in progress) will fix the node positions to better than the 25 \u00b5m sampling used here and test whether the CR1 free-end discrepancy is node position or something else. (iv) The load ladder (stage 4) will show whether the channel-ratio suppression relative to PPP-CONTAu is load or tip.')]),

      H1('6. Conclusion'),
      P('On a displacement-detecting instrument, moving the detection spot along the cantilever turns the cantilever transfer function from an assumption into a measurement. With a two-domain bias survey to remove electrostatics exactly, the quasi-static piezoresponse of PPLN converts to d\u2083\u2083 = 8.0 pm/V through the per-position force-curve sensitivity alone, and the contact potential comes out at +0.77 V independent of the cantilever. At the first contact resonance the enhancement over quasi-static varies by a factor 180 along the lever and equals Q at a single position, so Q-normalised CR1 amplitudes are not quantitative. An Euler\u2013Bernoulli model constrained only by resonance frequencies, Q and the static deflection shape predicts that enhancement to a few percent away from the node and returns d\u2083\u2083 = 7.97 pm/V from CR1 with a 1.07\u00d7 spread and one calibration constant. The same model predicts the CR2 and CR3 shapes and nodes but needs an empirical gain of 2.8 and 5.5 per mode, after which all three modes agree on d\u2083\u2083 to within 10 %.'),

      H1('Methods and data'),
      P('Instrument: Asylum Cypher (QPDI detection), Igor Pro automation via COM through the activemodemap package (AsylumInstrument, run_series). Data: D:\\User Data\\Liam\\ActiveModeMap\\DomainsB_SCMPIT \u2014 domains_bias_checkpoint_500nN_scmpit.npz (14 \u00d7 8 \u00d7 58 816 complex), Tune_SCMPIT_*.txt (136 files), FSCMPIT0044\u20130058.ibw (the eight stage-1 force curves, matched to positions by timestamp), preflight_result.json, preflight_walk_checkpoint.npz (19 positions at 10 \u00b5m, 500 nN). Analysis scripts: scripts\\scmpit\\analyze_stage1.py (channel decomposition), scripts\\scmpit\\analysis\\fit_eb.py, fit_eb_joint.py, fit_eb_noE.py (EB fits; _noE is the blind fit used in the text), higher_modes.py, plot_stage1.py, plot_higher.py. Figures: DomainsB_SCMPIT\\analysis\\figA\u2013E. Phase convention of the checkpoint: \u201cmodel\u201d (Cypher raw conjugated by tune_to_complex). Frequency decimation by 2 (29 408 points) was used for the EB analysis and figures; all reported numbers were checked against the full-resolution checkpoint.'),
      P([T('Dense-grid and load-ladder stages of the same campaign were running while this note was written and are not included.', { italics: true, color: '555555' })]),
    ]
  }]
});
Packer.toBuffer(doc).then(b => { fs.writeFileSync('SCMPIT_d33_recovery_note_2026-09-20.docx', b); console.log('written'); });
